### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kotelkonrad** [EmosewaPixel/GregsConstruct#1]
https://paste.dimdev.org/asanekatey.mccrash

**Comment by TheLimePixel** [comment]
As you can clearly read on the crash log, it's because it and PlusTiC have a duplicating material, Iridium (Though I'm sure there are more). Since the tool materials in this mod are generated from GregTech's, I can't make it configurable, so you'll need to disable in PlusTiC's config.

**Comment by gerb82** [comment]
I'm unsure of the practicality of this but i'll suggest it just in case: making something to try handle duplicate materials so that the mod doesn't generate resources that already exist from other mods/disables them once duplicates are found. Not sure if this will need to happen at the tinkers' level or if it can happen on the mod level, but just throwing the idea out there

**Comment by TheLimePixel** [comment]
Oh, right... I somehow didn't think about doing that.

**Comment by kotelkonrad** [comment]
thank you
